- // MIR for `le` before GVN
+ // MIR for `le` after GVN
  
  fn le(_1: u16) -> () {
      debug input => _1;
      let mut _0: ();
      let _2: bool;
      let mut _3: u32;
      let mut _4: u16;
      let mut _6: u32;
      let mut _7: u16;
      let mut _9: u32;
      let mut _10: u16;
      let mut _11: u32;
      scope 1 {
          debug yes => _2;
          let _5: bool;
          scope 2 {
              debug no => _5;
              let _8: bool;
              scope 3 {
                  debug runtime => _8;
              }
          }
      }
  
      bb0: {
          StorageLive(_2);
-         StorageLive(_3);
+         nop;
          StorageLive(_4);
          _4 = copy _1;
-         _3 = move _4 as u32 (IntToInt);
+         _3 = copy _1 as u32 (IntToInt);
          StorageDead(_4);
-         _2 = Ge(const U16_MAX_PLUS_ONE, move _3);
-         StorageDead(_3);
+         _2 = const true;
+         nop;
          StorageLive(_5);
          StorageLive(_6);
          StorageLive(_7);
          _7 = copy _1;
-         _6 = move _7 as u32 (IntToInt);
+         _6 = copy _3;
          StorageDead(_7);
-         _5 = Ge(move _6, const U16_MAX_PLUS_ONE);
+         _5 = const false;
          StorageDead(_6);
          StorageLive(_8);
          StorageLive(_9);
          StorageLive(_10);
          _10 = copy _1;
-         _9 = move _10 as u32 (IntToInt);
+         _9 = copy _3;
          StorageDead(_10);
          StorageLive(_11);
-         _11 = const core::num::<impl u16>::MAX as u32 (IntToInt);
-         _8 = Ge(move _9, move _11);
+         _11 = const 65535_u32;
+         _8 = Ge(copy _3, const 65535_u32);
          StorageDead(_11);
          StorageDead(_9);
          _0 = const ();
          StorageDead(_8);
          StorageDead(_5);
          StorageDead(_2);
          return;
      }
  }
  
